#! /bin/sh
#
# Put this line into your crontab (man crontab):
# 0,10,20,30,40,50 * * * * /path/to/miau/miau-check >/dev/null 2>&1
#
# ...where /path/to/miau is likely either $HOME/miau or /usr/bin.
#
# This will check for a running miau every 10 minutes.
#

# If miau can't be found automatically, you must define the location here
# MIAUBIN=/somewhere/else/miau

test "$1"       && MIAUDIR="$1"
test "$MIAUDIR" || MIAUDIR="$HOME/.miau"
if ! test -d "$MIAUDIR"; then
	echo "miau direcory not defined or found!"
	exit 1
fi

test "$2" && MIAUBIN="$2"
test ! "$MIAUBIN" -a -x "$MIAUDIR/miau" && MIAUBIN="$MIAUDIR/miau"
test ! "$MIAUBIN" -a -x "$HOME/miau/miau" && MIAUBIN="$HOME/miau/miau"
test ! "$MIAUBIN" -a -x "/usr/bin/miau" && MIAUBIN="/usr/bin/miau"
test ! "$MIAUBIN" -a -x "miau" && MIAUBIN="miau"
if ! test "$MIAUBIN"; then
	echo "miau binary not found or defined!"
	exit 1
fi

if test -r "$MIAUDIR/pid"; then
	PID="$(cat "$MIAUDIR/pid")"
	kill -0 "$PID" >/dev/null 2>&1 && exit 0
	rm -f "$MIAUDIR/pid"
fi
echo "Starting miau..."
"$MIAUBIN" -d "$miaudir"
exit $?
